### ISSUE TITLE
NodeJS Elasticsearch search returns promise instead of values

### ISSUE THREAD

**Issue by angelovancleef** [elastic/elasticsearch-js-legacy#17]
I made a request inside my Node server to Elasticsearch. This is working perfect, except that I always get a promise returned instead of the results.

When I console log the results they look perfect, but when I return them I either get nothing or a promise.

Can someone tell me the proper way to retrieve, and handle the data from Elasticsearch?

I am using VueJS with a Node server and the official Elasticsearch package.

```
    function getNewTest(client)
    {
        client.search({
            index: 'myIndex',
        }).then(function(resp) {
    
            return resp.hits.hits;
    
        }, function(err) {
    
            console.trace(err.message);
    
        });
    }
    
    let tests = getNewTest(client);
    console.log(tests);
    
    # Output: Promise { <pending> }
```

**EDIT:**
I changed my own code, now it returns an "undefined" to me.

```
getNewTest(client).then(function (response) {
           console.log(response);
        });
```

will return "undefined" to me. I changed my function to this:

```
async function getNewTest(client)
{
    await client.search({
        index: 'myIndex',
    }).then(function(resp) {

        console.log(resp.hits.hits, 'returned');
        return resp.hits.hits;

    }, function(err) {

        console.trace(err.message);

    });
}
```

When I would do 

```
let test = getNewTest(client);
```

it returns a promise to me.

**Comment by VikashKrChoudhary** [comment]
By seeing the above code which you have shared, below is the reason because of which it returns a promise.

**Reason:**
since `getNewTest` is an async function that returns a promise. So, to get the resolved value you should use await while calling the same.
Hence, it should be written like below,
`
let test = await getNewTest(client);
console.log(test); // resp.hits.hits
`
I hope it helps!
Thanks.

**Comment by VikashChoudahry** [comment]
Reason could be:

Since `getNewTest` is an async function that returns a promise. So, to get the resolved value you should use await while calling the same.
Hence, it should be written like below,

`let test = await getNewTest(client); console.log(test); // resp.hits.hits`

I hope this helps!
Thanks.
